### ISSUE TITLE
pendingTransactionInformation raising error

### ISSUE THREAD

**Issue by redcpp** [algorand/js-algorand-sdk#189]
Using the PureStake V2 API for the Testnet.

When calling pendingTransactionInformation rawResponse is wrongly encoded.

```js
const algosdk = require('algosdk')

async function main () {
  try {
    const algodToken = {
      "X-API-Key": "MYAPIKEY"
    }
    const algodServer = "https://testnet-algorand.api.purestake.io/ps2"
    const algodPort = ""
    
    
    const algodClient = new algosdk.Algodv2(algodToken, algodServer, algodPort)
    const pendingInfo = await algodClient.pendingTransactionInformation('KOO3XP5NXF6VJPJA6EG4GLU2PETF4YVFPDZA7MOCC3ZRLRZJAADA').do()
    console.log('pendingInfo', pendingInfo)
  } catch (error) {
    console.log(error)
  }
}

main()
```

Error:

```js
SyntaxError: Unexpected token g in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/redcpp/Algo/Tutorials/algo-ipfs/node_modules/superagent/lib/node/parsers/json.js:11:35)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  rawResponse: 'g69jb25maXJtZWQtcm91bmTOAHkzb6pwb29sLWVycm9yoKN0eG6Co3NpZ8RAivx0vTOT4dNPaKnMa676XeDhSzESfUgD67VamGQ31YIuIXpZVxGwVpsU+JiPym4Gm3rLiC2PeiNLFwS3wD9wCKN0eG6Jo2ZlZc0D6KJmds4AeTNto2dlbqx0ZXN0bmV0LXYxLjCiZ2jEIEhjtRiks8hOyBDyLU8QgcsPcfBZp6wg3sYvf3DlCToiomx2zgB5N1Wkbm90ZcQ82TpoZWxsby50eHQgLSBRbVZGZUFTblZoVkZYcUZXYzd1ajQ3Z1Exd3lQYjlGc25qVWhwMkdDU0FQcTNYo3JjdsQgLtXhttJ/xfp8XKiYmt/t/rcPGGYRTkfoq0V3/ZVAwP6jc25kxCAu1eG20n/F+nxcqJia3+3+tw8YZhFOR+irRXf9lUDA/qR0eXBlo3BheQ==',
  statusCode: 200,
  response: undefined
}
```

It works from bash:

```bash
curl -X GET "https://testnet-algorand.api.purestake.io/ps2/v2/transactions/pending/KOO3XP5NXF6VJPJA6EG4GLU2PETF4YVFPDZA7MOCC3ZRLRZJAADA" -H "accept: application/json" -H "x-api-key: MYAPIKEY"
```

Giving output:

```json
{
  "confirmed-round": 7943023,
  "pool-error": "",
  "txn": {
    "sig": "ivx0vTOT4dNPaKnMa676XeDhSzESfUgD67VamGQ31YIuIXpZVxGwVpsU+JiPym4Gm3rLiC2PeiNLFwS3wD9wCA==",
    "txn": {
      "fee": 1000,
      "fv": 7943021,
      "gen": "testnet-v1.0",
      "gh": "SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=",
      "lv": 7944021,
      "note": "2TpoZWxsby50eHQgLSBRbVZGZUFTblZoVkZYcUZXYzd1ajQ3Z1Exd3lQYjlGc25qVWhwMkdDU0FQcTNY",
      "rcv": "F3K6DNWSP7C7U7C4VCMJVX7N723Q6GDGCFHEP2FLIV373FKAYD7LT2MU2I",
      "snd": "F3K6DNWSP7C7U7C4VCMJVX7N723Q6GDGCFHEP2FLIV373FKAYD7LT2MU2I",
      "type": "pay"
    }
  }
}
```

**Comment by redcpp** [comment]
Duplicate of https://github.com/algorand/js-algorand-sdk/issues/173
