### ISSUE TITLE
Generating a new LogicSigAccount throws an error when a compiled teal program is passed to it

### ISSUE THREAD

**Issue by codemaster101** [algorand/js-algorand-sdk#606]
### Subject of the issue

Hi, so we started developing a solution which would involve signing sending offline transactions through a delegated smart signature (for which we were provided a python script (since the algorand js sdk does not yet support generating teal files as far as I know)). The generated teal program was then sent to the node to be compiled, and the compiled program was then fed to the LogicSigAccount constructor of the JS SDK. However, this threw an error. 
### Your environment

* Software version: `algod -v`
```
algorand@algorand-1:~$ algod -v -d /var/lib/algorand/
12885426176
3.8.0.stable [rel/stable] (commit #d867a094)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```
* Node status if applicable: `goal node status`
```
algorand@algorand-1:~$ goal node status -d /var/lib/algorand/
Last committed block: 22709883
Time since last block: 190673.3s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/d5ac876d7ede07367dbaa26e149aa42589aac1f7
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/d5ac876d7ede07367dbaa26e149aa42589aac1f7
Round for next consensus protocol: 22709884
Next consensus protocol supported: true
Last Catchpoint: 22700000#CCEO7JIBZY72U5IBHKDM7KY2TEVZBDYMJORJNCH5KDTFV6F3S45A
Genesis ID: testnet-v1.0
Genesis hash: SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=
```
* Operating System details. : LINUX

### Steps to reproduce
I am going to describe the issue in detail so that it can be reproduced.

1. The python program that we used to generate the teal program:

```
from pyteal import *

def delegate(proxy, endround, f):
  keyreg_txt = Bytes("keyreg")
  keyreg32 = Bytes("{:<32}".format("keyreg"))
  prev = Int(0)

  program = And(
    # 1. Chack validity of the keyreg itself
    Txn.type_enum() == TxnType.KeyRegistration,
    Txn.rekey_to() == Global.zero_address(),
    Txn.fee() == Int(0),
    Txn.first_valid() % Int(500) == Int(0),
    Txn.first_valid() <= Int(endround),
    Txn.last_valid() == Txn.first_valid() + Int(500),
    Txn.lease() == keyreg32,
    Txn.group_index() > Int(0),

    # 2. Check validity of companion pay transaction
    Gtxn[prev].type_enum() == TxnType.Payment,
    Gtxn[prev].amount() == Int(0),
    Gtxn[prev].rekey_to() == Global.zero_address(),
    Gtxn[prev].close_remainder_to() == Global.zero_address(),
    Gtxn[prev].sender() == Addr(proxy),
    Gtxn[prev].receiver() == Txn.sender(),
    Gtxn[prev].note() == keyreg_txt
  )

  compiled = compileTeal(
    ast=program,
    mode=Mode.Signature,
    version=6,
    assembleConstants=True
  )

  f.write(compiled)

def main():
  import sys, os

  print("Usage: python", sys.argv[0], "proxyAddr [endRound [outFile]]")
  print("  proxyAddr - address that can authorize keyreg")
  print("  endRound - expiration round for logicsig validity (default=30M)")
  print("  outFile - name of output file (default=logicsig.teal)")

  # Read the proxy and optional end-round from arguments
  if len(sys.argv) < 2:
    sys.exit()
  proxy = sys.argv[1]

  if len(sys.argv) > 2:
    endround = int(sys.argv[2])
  else:
    endround = 30000000

  if len(sys.argv) > 3:
    outfile = sys.argv[3]
  else:
    outfile="./logicsig.teal"

  f = open(outfile, "w")
  delegate(proxy, endround, f)

if __name__ == "__main__":
```

1.1 This python program generated the following teal file:

```
scripts$ cat logicsig-VIDD52LL2BAUOTUGHZLNA4PIYVBVUX5U6IG3J5UMWM32V2IIFPQAAO564U.teal   
#pragma version 6
intcblock 0 500
txn TypeEnum
pushint 2 // keyreg
==
txn RekeyTo
global ZeroAddress
==
&&
txn Fee
intc_0 // 0
==
&&
txn FirstValid
intc_1 // 500
%
intc_0 // 0
==
&&
txn FirstValid
intc_0 // 0
<=
&&
txn LastValid
txn FirstValid
intc_1 // 500
+
==
&&
txn Lease
pushbytes 0x6b65797265672020202020202020202020202020202020202020202020202020 // "keyreg                          "
==
&&
txn GroupIndex
intc_0 // 0
>
&&
intc_0 // 0
gtxns TypeEnum
pushint 1 // pay
==
&&
intc_0 // 0
gtxns Amount
intc_0 // 0
==
&&
intc_0 // 0
gtxns RekeyTo
global ZeroAddress
==
&&
intc_0 // 0
gtxns CloseRemainderTo
global ZeroAddress
==
&&
intc_0 // 0
gtxns Sender
pushbytes 0xaa063ee96bd041474e863e56d071e8c5435a5fb4f20db4f68cb337aae9082be0 // VIDD52LL2BAUOTUGHZLNA4PIYVBVUX5U6IG3J5UMWM32V2IIFPQAAO564U
==
&&
intc_0 // 0
gtxns Receiver
txn Sender
==
&&
intc_0 // 0
gtxns Note
pushbytes 0x6b6579726567 // "keyreg"
==
&&
```

2. We then passed the above teal file as a Buffer to the node using this endpoint:
```
      const tealProgram = fs.readFileSync(`${process.cwd()}/scripts/logicsig-${proxyAddress}.teal`);
      const compiledProgram = await algodClient.compile(new Uint8Array(tealProgram)).do();
```

2.1 And it returned the following program:
```
06200200f40331108102123120320312103101221210310223182212103102220e103104310223081210310680206b6579726567202020202020202020202020202020202020202020202020202012103116220d102238108101121022380822121022382032031210223809320312102238008020aa063ee96bd041474e863e56d071e8c5435a5fb4f20db4f68cb337aae9082be012102238073100121022380580066b6579726567121043
```

3. Following which we tried to generate the LogicSigAccount using:
```
        const lsig = new algosdk_1.LogicSigAccount(program, args);
```

This calls the readProgram function in the algosdk but **it does not work well**
and we run into the following error:
```
Error: invalid instruction
    at readProgram (./node_modules/algosdk/src/logic/logic.ts:214:13)
    at Object.checkProgram (./node_modules/algosdk/src/logic/logic.ts:270:18)
    at new LogicSig (./node_modules/algosdk/src/logicsig.ts:52:16)
    at new LogicSigAccount (./node_modules/algosdk/src/logicsig.ts:214:17)
```

### Expected behaviour

Successfully generates the LogicSigAccount Class.

### Actual behaviour
The read program throws a bug on the program that is being passed to it:

I added a few logs to the algosdk itself to see what error is being thrown and it seems the read program is called a few times.
These are the logs from each call:
On being passed a program and no args:  `        const lsig = new algosdk_1.LogicSigAccount(program, args);`
```
06200200f40331108102123120320312103101221210310223182212103102220e103104310223081210310680206b6579726567202020202020202020202020202020202020202020202020202012103116220d102238108101121022380822121022382032031210223809320312102238008020aa063ee96bd041474e863e56d071e8c5435a5fb4f20db4f68cb337aae9082be012102238073100121022380580066b6579726567121043 undefined (args)
{
  op: {
    Opcode: 6,
    Name: 'ecdsa_pk_decompress',
    Args: 'B',
    Returns: 'BB',
    Cost: 650,
    Size: 2,
    Doc: 'decompress pubkey A into components X, Y',
    DocExtra: 'The 33 byte public key in a compressed form to be decompressed into X and Y (top) components. All values are big-endian encoded.',
    ImmediateNote: '{uint8 curve index}',
    Groups: [ 'Arithmetic' ]
  }
}
6
{ size: 2 }
{
  op: {
    Opcode: 0,
    Name: 'err',
    Cost: 1,
    Size: 1,
    Doc: 'Fail immediately.',
    Groups: [ 'Flow Control' ]
  }
}
0
{ size: 1 }
{
  op: {
    Opcode: 0,
    Name: 'err',
    Cost: 1,
    Size: 1,
    Doc: 'Fail immediately.',
    Groups: [ 'Flow Control' ]
  }
}
0
{ size: 1 }
{
  op: {
    Opcode: 2,
    Name: 'keccak256',
    Args: 'B',
    Returns: 'B',
    Cost: 130,
    Size: 1,
    Doc: 'Keccak256 hash of value A, yields [32]byte',
    Groups: [ 'Arithmetic' ]
  }
}
2
{ size: 1 }
{
  op: {
    Opcode: 0,
    Name: 'err',
    Cost: 1,
    Size: 1,
    Doc: 'Fail immediately.',
    Groups: [ 'Flow Control' ]
  }
}
0
{ size: 1 }
{
  op: {
    Opcode: 0,
    Name: 'err',
    Cost: 1,
    Size: 1,
    Doc: 'Fail immediately.',
    Groups: [ 'Flow Control' ]
  }
}
0
{ size: 1 }
{ op: undefined }
f
op is undefined...
Error: invalid instruction
    at readProgram (./node_modules/algosdk/src/logic/logic.ts:214:13)
    at Object.checkProgram (./node_modules/algosdk/src/logic/logic.ts:270:18)
    at new LogicSig (./node_modules/algosdk/src/logicsig.ts:52:16)
    at new LogicSigAccount (./node_modules/algosdk/src/logicsig.ts:214:17)
```

**Comment by barnjamin** [comment]
Hi @codemaster101 

I just tried to replicate given the compiled program and I found that it does seem to work for me
![image](https://user-images.githubusercontent.com/520236/178249752-bb420cc9-6a70-4d7a-ada8-cf5dc4ebc8ba.png)


What version of the SDK are you on? it may be that a newer version contains the opcode that claims to be undefined?

**Comment by codemaster101** [comment]
Hmm, I also updated the js-algorand-sdk and it seems to work for me as well. @barnjamin 
Thanks
