### ISSUE TITLE
superagent very old deprecated version

### ISSUE THREAD

**Issue by scholtz** [algorand/js-algorand-sdk#648]
### Subject of the issue

Please upgrade superagent library. Version 6 is deprecated. https://www.npmjs.com/package/superagent

I am facing issues superagent crashing the typescript app.. Unable to catch error in try catch.

Error: Network request error. Received status 400: TransactionPool.Remember: txn dead: round 1742449 outside of 1741200--1742200
    at Request.callback (node_modules/algosdk/node_modules/superagent/src/node/index.js:879:15)
    at fn (node_modules/algosdk/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.<anonymous> (node_modules/algosdk/node_modules/superagent/src/node/parsers/image.js:8:5)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1340:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Or better upgrade to something tested by millions of people eg axios

### Your environment

latest

### Steps to reproduce

1. start app ts-node main.ts
2. wait till application crashes

### Expected behaviour

App running 

### Actual behaviour

App crashes

**Comment by scholtz** [comment]
actually it is the application use case that i am getting that error, but i need the superagent not to crash the app

**Comment by jasonpaulos** [comment]
This was solved by #676 by migrating to fetch
